In [4]:
import numpy as np

In [5]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [6]:
# Now let's multiply each sequence by 2
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 31.2 ms, sys: 62.5 ms, total: 93.8 ms
Wall time: 73.9 ms


In [7]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 531 ms, sys: 469 ms, total: 1 s
Wall time: 1.03 s


In [8]:
# NumPy based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparnts
# and use significantly less memory

In [9]:
# 4.1 The NumPy ndarray
import numpy as np

In [10]:
# Generate some random data

In [11]:
data = np.random.randn(2, 3)

In [12]:
data

array([[-0.3744207 , -0.40647836,  0.74664912],
       [ 1.49605631, -1.04013915,  2.52542572]])

In [13]:
# Then write mathematical operations with data:
data * 10

array([[ -3.74420696,  -4.06478362,   7.46649117],
       [ 14.96056309, -10.40139149,  25.25425724]])

In [14]:
data + data

array([[-0.74884139, -0.81295672,  1.49329823],
       [ 2.99211262, -2.0802783 ,  5.05085145]])

In [15]:
# In the first example, all of the elements have been multiplied by 10.
# In the second, the corresponding values in each "cell" in the array have been added to each other.

In [16]:
# Every array has a shape
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
# Creating ndarrays
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

In [19]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [20]:
# Nestede sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [21]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
# Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape
# inferred from the data
arr2.ndim

2

In [23]:
arr2.shape

(2, 4)

In [24]:
# To create a higer dimensional array with these methods, pass a tuple for the shape:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[2.14775316e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [30]:
# Note!: It is not safe to assume that np.empty will return an array of 
# all zeros. In some cases, it may return uninitialized "garbage" values

In [33]:
# arrange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
# Data Types for ndarrays
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [36]:
arr1.dtype

dtype('float64')

In [37]:
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1, 2, 3, 4, 5])

In [39]:
arr.dtype

dtype('int64')

In [40]:
float_arr = arr.astype(np.float64)

In [41]:
float_arr.dtype

dtype('float64')

In [44]:
# In this example, integers were cast to floating point. If I cast some floating-point
# numbers to be integer dtype, the decimal part will be truncated:

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [45]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [46]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [47]:
# If you have an array of strings representing numbers, you can use astype to convert them to numeric form:

numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [48]:
# Arithmetic with NumPy Arrays

arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [49]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [51]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:

1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [53]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [54]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [55]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [56]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [ ]:
# Operations between differently sized arrays is called broadcasting