In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
# Now let's multiply each sequence by 2
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 31.2 ms, sys: 31.2 ms, total: 62.5 ms
Wall time: 93.6 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 625 ms, sys: 422 ms, total: 1.05 s
Wall time: 1.04 s


In [6]:
# NumPy based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparnts
# and use significantly less memory

In [7]:
# 4.1 The NumPy ndarray
import numpy as np

In [8]:
# Generate some random data

In [9]:
data = np.random.randn(2, 3)

In [10]:
data

array([[-0.85018625,  1.50843849,  1.37842084],
       [-1.68725652,  0.68984547,  0.23304834]])

In [11]:
# Then write mathematical operations with data:
data * 10

array([[ -8.50186246,  15.08438488,  13.78420839],
       [-16.87256518,   6.89845473,   2.33048344]])

In [12]:
data + data

array([[-1.70037249,  3.01687698,  2.75684168],
       [-3.37451304,  1.37969095,  0.46609669]])

In [13]:
# In the first example, all of the elements have been multiplied by 10.
# In the second, the corresponding values in each "cell" in the array have been added to each other.

In [14]:
# Every array has a shape
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [16]:
# Creating ndarrays
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

In [17]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [18]:
# Nestede sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [19]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
# Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape
# inferred from the data
arr2.ndim

2

In [21]:
arr2.shape

(2, 4)

In [22]:
# To create a higer dimensional array with these methods, pass a tuple for the shape:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[1.7635519e-316, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]]])

In [25]:
# Note!: It is not safe to assume that np.empty will return an array of 
# all zeros. In some cases, it may return uninitialized "garbage" values

In [26]:
# arrange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# Data Types for ndarrays
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [30]:
arr = np.array([1, 2, 3, 4, 5])

In [31]:
arr.dtype

dtype('int64')

In [32]:
float_arr = arr.astype(np.float64)

In [33]:
float_arr.dtype

dtype('float64')

In [34]:
# In this example, integers were cast to floating point. If I cast some floating-point
# numbers to be integer dtype, the decimal part will be truncated:

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [35]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [36]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [37]:
# If you have an array of strings representing numbers, you can use astype to convert them to numeric form:

numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [38]:
# Arithmetic with NumPy Arrays

arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [39]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [41]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:

1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [43]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [44]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [45]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [46]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [47]:
# Operations between differently sized arrays is called broadcasting

In [48]:
# Basic Indexing and Slicing
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr[5]

5

In [51]:
arr[5:8]

array([5, 6, 7])

In [52]:
arr[5:8] = 12

In [53]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [54]:
arr_slice = arr[5:8]

In [55]:
arr_slice

array([12, 12, 12])

In [56]:
arr_slice[1] = 12345

In [57]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [58]:
# The "bare" slice [:] will assign to all values in an array
arr_slice[:] = 64

In [59]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [60]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [61]:
arr2d[2]

array([7, 8, 9])

In [62]:
arr2d[0][2]

3

In [63]:
arr2d[0, 2]

3

In [64]:
# 2 x 2 x 3 array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [65]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
# This is a 2 x 3 array

In [68]:
# Both scalar values and arrays can be assigned to arr3d[0]:
old_values = arr3d[0].copy()
arr3d[0] = 42

In [69]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [70]:
arr3d[0] = old_values

In [71]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [72]:
# Indexing with slices

In [73]:
# Like one-dimensional objects, ndarrays can be sliced with the familiar syntax
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [74]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [75]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
# You can pass multiple slices
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [78]:
# Getting lower dimensional slices
arr2d[1, :2]

array([4, 5])

In [79]:
# Similarly, you can select the third column but only the first two rows:
arr2d[:2, 2]

array([3, 6])

In [80]:
# Boolean Indexing
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [81]:
data = np.random.randn(7, 4)

In [82]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [83]:
data

array([[-0.8113128 ,  1.26293746,  0.15342613,  0.28520269],
       [-0.51214205,  0.50801387,  0.91477932,  1.25541133],
       [ 0.3543527 , -0.22334539,  0.31907782,  0.54789754],
       [-0.83707349, -1.06214621,  1.81270845,  0.49597007],
       [-0.37748842, -0.41497952, -1.21174044,  1.38420804],
       [-0.01238028, -0.86440694,  1.25384062,  1.72221262],
       [-0.40776625, -0.14811825,  0.01375183, -1.13945583]])

In [84]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [85]:
data[names == 'Bob']

array([[-0.8113128 ,  1.26293746,  0.15342613,  0.28520269],
       [-0.83707349, -1.06214621,  1.81270845,  0.49597007]])

In [86]:
data[names == 'Bob', 2:]

array([[0.15342613, 0.28520269],
       [1.81270845, 0.49597007]])

In [87]:
data[names == 'Bob', 3]

array([0.28520269, 0.49597007])

In [88]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [89]:
data[~(names == 'Bob')]

array([[-0.51214205,  0.50801387,  0.91477932,  1.25541133],
       [ 0.3543527 , -0.22334539,  0.31907782,  0.54789754],
       [-0.37748842, -0.41497952, -1.21174044,  1.38420804],
       [-0.01238028, -0.86440694,  1.25384062,  1.72221262],
       [-0.40776625, -0.14811825,  0.01375183, -1.13945583]])

In [90]:
# The ~ operator can be useful when you want to invert a general condition:
cond = names == 'Bob'

In [91]:
data[~cond]

array([[-0.51214205,  0.50801387,  0.91477932,  1.25541133],
       [ 0.3543527 , -0.22334539,  0.31907782,  0.54789754],
       [-0.37748842, -0.41497952, -1.21174044,  1.38420804],
       [-0.01238028, -0.86440694,  1.25384062,  1.72221262],
       [-0.40776625, -0.14811825,  0.01375183, -1.13945583]])

In [92]:
mask = (names == 'Bob') | (names == 'Will')

In [93]:
mask

array([ True, False,  True,  True,  True, False, False])

In [94]:
data[data < 0] = 0

In [95]:
# Selecting data from an array by boolean indexing always creates a copy of the data
# even if the returned array is unchanged
data[mask]

array([[0.        , 1.26293746, 0.15342613, 0.28520269],
       [0.3543527 , 0.        , 0.31907782, 0.54789754],
       [0.        , 0.        , 1.81270845, 0.49597007],
       [0.        , 0.        , 0.        , 1.38420804]])

In [96]:
data[names != 'Joe'] = 7

In [97]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.50801387, 0.91477932, 1.25541133],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.25384062, 1.72221262],
       [0.        , 0.        , 0.01375183, 0.        ]])

In [99]:
# Fancy Indexing
arr = np.empty((8, 4))

for i in range(8):
    arr[i] = i

In [100]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [101]:
# To select out a subset of the rows in a particular order, you can simply pass a list of 
# ndarrayof integers specifying the desired order:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [103]:
# Using negative indixes selects rows from the end:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [104]:
# Passing multiple index arrays does something slightly different; it selects a one-dimensional array
# of elements corresponding to each tuple of indices:
arr = np.arange(32).reshape((8, 4))

In [105]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [106]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [107]:
# Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.

In [108]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [109]:
# Keep in mind that fancy indexing, unlike slicing, always copies that data into a new array.

In [121]:
# Transposing Arrays and Swapping Axes
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [123]:
# When doing matrix computations, you may do this very often
# For example, when computing the inner matrix product using np.dot:
arr = np.random.randn(6, 3)
arr

array([[ 0.5700827 , -0.80292213,  0.46134633],
       [-1.36134599,  0.45365201,  0.68994714],
       [-1.3129763 , -1.13726339,  0.16825996],
       [ 0.43518546, -0.59499203, -0.23526942],
       [-0.97132427,  0.06606549, -0.32017678],
       [ 0.61372377, -0.14827523,  0.55059045]])

In [124]:
np.dot(arr.T, arr)

array([[ 5.41167805e+00,  3.78759378e-03, -3.50652443e-01],
       [ 3.78759378e-03,  2.52421782e+00, -2.11593298e-01],
       [-3.50652443e-01, -2.11593298e-01,  1.17819362e+00]])