In [1]:
import numpy as np

In [10]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [11]:
# Now let's multiply each sequence by 2
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 0 ns, sys: 15.6 ms, total: 15.6 ms
Wall time: 33 ms


In [12]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 531 ms, sys: 406 ms, total: 938 ms
Wall time: 952 ms


In [13]:
# NumPy based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparnts
# and use significantly less memory

In [15]:
# 4.1 The NumPy ndarray
import numpy as np

In [16]:
# Generate some random data

In [17]:
data = np.random.randn(2, 3)

In [18]:
data

array([[ 1.01992628,  2.26331843, -0.49896377],
       [ 0.08453415,  0.74298176,  0.44363875]])

In [20]:
# Then write mathematical operations with data:
data * 10

array([[10.19926284, 22.63318427, -4.98963768],
       [ 0.84534145,  7.42981757,  4.43638755]])

In [21]:
data + data

array([[ 2.03985257,  4.52663685, -0.99792754],
       [ 0.16906829,  1.48596351,  0.88727751]])

In [22]:
# In the first example, all of the elements have been multiplied by 10.
# In the second, the corresponding values in each "cell" in the array have been added to each other.

In [23]:
# Every array has a shape
data.shape

(2, 3)

In [26]:
data.dtype

dtype('float64')

In [27]:
# Creating ndarrays
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

In [28]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [29]:
# Nestede sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

In [30]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
# Since data2 was a list of lists, the NumPy array arr2 has two dimensions with shape
# inferred from the data
arr2.ndim

2

In [32]:
arr2.shape

(2, 4)